services:
  api:
    build: ./api
    volumes:
      - ./api:/src
      - ~/.aws:/tmp/.aws
    working_dir: /src
    entrypoint: ['poetry', 'run']
    environment:
      - HOME=/tmp
    ports:
      - 8082:8000
    command: ['uvicorn', 'main:app', '--reload', '--host=0.0.0.0']
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
  web:
    build: ./web
    volumes:
    - ./web:/src
    - ~/.aws:/home/node/.aws
    working_dir: /src
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    ports:
      - 8081:8080
    command: ['npm', 'run', 'serve']